@startuml
autonumber "[<b>[000]"
actor User
database RedisTokenDatabase

title: Login Procedure

User -> WebApp: Submit login form
WebApp -> TokenService:  \
Send login credentials: \n\
 Content-Type: application/x-www-form-urlencoded \n\
 {\n \
  "email": "dummy@test.com",\n\
  "password": "dummy" \n\
 }

TokenService -> UserService: \
Forward login credentials: \n\n\
 Content-Type: application/json \n\
 {\n \
  "email": "dummy@test.com",\n\
  "password": "dummy" \n\
 }

alt Valid credentials
UserService -> TokenService: \
 Content-Type: application/json \n\
 {\n \
  "email": "dummy@test.com",\n\
  "username": "dummy" \n\
  ...profileInfo \n\
 }

TokenService -> RedisTokenDatabase: \
  Store token

TokenService -> WebApp: \
 Content-Type: application/json \n\
 Authorization: Bearer <(jwt)token> \n\
 {\n \
  "email": "dummy@test.com",\n\
  "username": "dummy" \n\
  ...profileInfo \n\
 }

WebApp -> User: Authenticated \n\
  Owner of JWT to access services

else Failure
UserService -> TokenService: \
 Content-Type: application/json \n\
 {\n \
  ...errorMessage \n\
 }
TokenService -> WebApp: \
 Forward Error Message\n\
 Content-Type: application/json \n\
 {\n \
  ...errorMessage \n\
 }

WebApp -> User: Not Authenticated \n\
  Show error message to user.
end

@enduml
